remote_theme: christianezeani/panthera-jekyll


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Kapurichino
subtitle: "게임 프로그래머"

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; Christian Ezeani"

# Side Menu Links
menu:
  - text: "포트폴리오"
    link: /
    icon: ""

  - text: 기술
    link: /skills-and-offers
    icon: ""

  - text: "문의"
    link: /contact
    icon: ""

  - text: "이력"
    link: /resume
    icon: ""

  - text: "포스트"
    link: /blog
    icon: ""

# Socialmedia Icons
social_icons:
 #- name: linkedin
 #  link: https://www.linkedin.com/christianezeani
 #  icon: fab fa-linkedin

  - name: github
    link: https://github.com/kapurichino
    icon: fab fa-github-square

 # - name: facebook
 #   link: https://www.facebook.com/christian.ezeani.cyb
 #   icon: fab fa-facebook-square

 # - name: twitter
 #   link: https://www.twitter.com/christianezeani
 #   icon: fab fa-twitter


    
